# Generated by Django 2.2.13 on 2020-06-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thread_id', models.IntegerField()),
                ('category', models.CharField(choices=[('GEN', 'Genre'), ('TIM', 'Timed'), ('TIE', 'Tier'), ('COL', 'Collection'), ('CLA', 'Classic'), ('PUZ', 'Puzzle'), ('SPE', 'Special')], default='TIM', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('avatar_url', models.URLField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awc.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awc.User')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('mode', models.CharField(choices=[('D', 'Default'), ('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard'), ('B', 'Bonus')], default='D', max_length=1)),
                ('text', models.CharField(max_length=250)),
                ('extra', models.CharField(blank=True, default='', max_length=250)),
                ('extra_newline', models.BooleanField(default=False)),
                ('bonus', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awc.Challenge')),
            ],
        ),
    ]
