# Generated by Django 2.2.13 on 2020-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0002_submission_submission_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='extra',
            field=models.TextField(blank=True, default=''),
        ),
    ]
