# Generated by Django 2.2.13 on 2020-07-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0004_auto_20200704_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='has_prerequisites',
            field=models.BooleanField(default=False),
        ),
    ]
