# Generated by Django 2.2.13 on 2020-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0005_challenge_has_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='has_prerequisites',
        ),
        migrations.AddField(
            model_name='challenge',
            name='prerequisites',
            field=models.ManyToManyField(to='awc.Challenge'),
        ),
    ]
