# Generated by Django 2.2.13 on 2020-07-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0006_auto_20200711_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='anime_link',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requirement',
            name='anime_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
