# Generated by Django 2.2.13 on 2020-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0007_auto_20200722_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allows_up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
