# Generated by Django 2.2.13 on 2020-08-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0008_challenge_allows_up_to_date'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(	
            state_operations=[
                migrations.AlterField(
                    model_name='submission',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
                ),
                migrations.DeleteModel(
                    name='User',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='User',
                    table='core_user',
                )
            ],
        ),
    ]
