# Generated by Django 2.2.13 on 2020-09-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0009_auto_20200829_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='force_raw_edit',
            field=models.BooleanField(default=False),
        ),
    ]
