# Generated by Django 2.2.13 on 2020-09-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0010_requirement_force_raw_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='raw_requirement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
