# Generated by Django 2.2.16 on 2021-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awc', '0013_auto_20200905_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_thread_id',
            field=models.IntegerField(default=4446),
        ),
    ]
