# Generated by Django 2.2.13 on 2020-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='User',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=50)),
                        ('user_id', models.IntegerField()),
                        ('avatar_url', models.URLField()),
                        ('is_admin', models.BooleanField(default=False)),
                    ],
                ),
            ],
            database_operations=[],
        ),
    ]
